# Generated by Django 4.2.4 on 2023-10-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='main_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
