# Generated by Django 4.2.4 on 2023-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0004_industry_description_en_industry_description_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='image_thumbnail',
            field=models.ImageField(help_text='Best size: 476*694 PX', upload_to='industry/thumbs'),
        ),
    ]
