# Generated by Django 5.0.6 on 2024-06-08 07:14

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('founded', models.DateTimeField(default=django.utils.timezone.now)),
                ('line', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='brands')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], max_length=1)),
                ('keywords', models.CharField(max_length=300, null=True)),
                ('seo_description', models.TextField(null=True)),
            ],
        ),
    ]
