# Generated by Django 5.0.6 on 2024-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_rename_category_line_remove_brands_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='line',
            field=models.ManyToManyField(related_name='brands', to='brands.line'),
        ),
    ]
