# Generated by Django 5.0.6 on 2024-06-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brands_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='brands/thumbnail'),
        ),
    ]
