# Generated by Django 5.0.6 on 2024-06-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brands_thumbnail'),
        ('houses', '0002_houses_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='line',
            field=models.ManyToManyField(related_name='brands', to='houses.houses'),
        ),
    ]
