# Generated by Django 5.0.6 on 2024-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_alter_brands_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='banner',
            field=models.ImageField(null=True, upload_to='brands/banner'),
        ),
    ]
