# Generated by Django 5.0.6 on 2024-06-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_brands_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
    ]
