# Generated by Django 5.0.6 on 2024-07-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_delete_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
