# Generated by Django 4.2.4 on 2023-10-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_thumbnail',
        ),
    ]
