# Generated by Django 5.0.6 on 2024-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(null=True, upload_to='news/banner'),
        ),
    ]
