# Generated by Django 4.2.4 on 2023-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='news/thumb'),
        ),
    ]
