# Generated by Django 4.2.4 on 2023-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_title_en_category_title_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(help_text='Best size: 370*250 PX', null=True, upload_to='news/thumb'),
        ),
    ]
