# Generated by Django 5.0.6 on 2024-06-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_houses_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='banner',
            field=models.ImageField(null=True, upload_to='houses/banner'),
        ),
    ]
