# Generated by Django 5.0.6 on 2024-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='banner',
            field=models.ImageField(null=True, upload_to='contact/banner'),
        ),
    ]
