# Generated by Django 4.2.4 on 2023-10-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinformation',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='whatsapp',
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, null=True)),
                ('icon', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('main_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='home.siteinformation')),
            ],
        ),
    ]
