# Generated by Django 5.0.6 on 2024-06-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpfulLinks_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('main_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links2', to='home.siteinformation')),
            ],
        ),
    ]
