# Generated by Django 4.2.4 on 2023-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
