# Generated by Django 4.2.4 on 2023-10-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_siteinformation_logo_dark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='logo',
            new_name='logo_light',
        ),
    ]
