# Generated by Django 5.0.6 on 2024-06-15 12:02

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_helpfullinks_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('about_img', models.ImageField(upload_to='home/about')),
                ('about', tinymce.models.HTMLField()),
                ('about2', tinymce.models.HTMLField()),
                ('video', models.FileField(blank=True, null=True, upload_to='home/video')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='home/brands')),
                ('home_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='home.homedata')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='home/sliders')),
                ('home_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='home.homedata')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='home/icons')),
                ('home_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='home.homedata')),
            ],
        ),
    ]
