# Generated by Django 4.2.4 on 2023-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_logo_siteinformation_logo_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='logo_dark',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
    ]
