# Generated by Django 5.0.6 on 2024-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homedata_brands_slider_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='data',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
