# Generated by Django 5.0.6 on 2024-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_brands_link_statistics_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='video_banner',
            field=models.ImageField(null=True, upload_to='home/banner'),
        ),
    ]
