# Generated by Django 4.2.4 on 2023-10-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
