# Generated by Django 5.0.6 on 2024-06-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_statistics_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='data',
            field=models.IntegerField(null=True),
        ),
    ]
