# Generated by Django 4.2.4 on 2023-10-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_features_description_en_features_description_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpfulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('main_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Links', to='home.siteinformation')),
            ],
        ),
    ]
