# Generated by Django 5.0.6 on 2024-06-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_statistics_banner_homedata_statistics_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
