# Generated by Django 4.2.4 on 2023-10-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_helpfullinks_title_en_helpfullinks_title_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpfullinks',
            name='main_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='home.siteinformation'),
        ),
    ]
