# Generated by Django 5.0.6 on 2024-06-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
