# Generated by Django 5.0.6 on 2024-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homedata_about_alter_homedata_about2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedata',
            name='description',
        ),
        migrations.AddField(
            model_name='homedata',
            name='sub_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
