# Generated by Django 5.0.6 on 2024-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_homedata_description_homedata_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='about2',
            field=models.TextField(null=True),
        ),
    ]
