# Generated by Django 5.0.6 on 2024-07-02 09:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homedata_about_alter_homedata_about2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='about',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='about2',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
