# Generated by Django 4.2.4 on 2023-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='google_map',
            field=models.URLField(null=True),
        ),
    ]
