# Generated by Django 4.2.4 on 2023-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_contactus_email_alter_contactus_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='google_map',
            field=models.URLField(null=True),
        ),
    ]
