# Generated by Django 4.2.4 on 2023-10-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_remove_contactus_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
