# Generated by Django 5.0.6 on 2024-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='banner',
            field=models.ImageField(null=True, upload_to='about/banner'),
        ),
    ]
